# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: clang-format

permissions:
  # Grant read permissions to private container images.
  packages: read

on:
  push:
    paths:
      - '.github/workflows/clang-format.yml'
      - 'scripts/clang-format.sh'
      - '**.c'
      - '**.cpp'
      - '**.h'

  pull_request:
    paths:
      - '.github/workflows/clang-format.yml'
      - 'scripts/clang-format.sh'
      - '**.c'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/intel/fpga-runtime-for-opencl/ubuntu-22.04-dev:main

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run clang-format on source files
        run: ./scripts/clang-format.sh --verbose

      - name: ensure source files are unchanged
        run: git diff --exit-code
