# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: run clang-format

# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  # Grant read permissions to repository in case it is not a forked public
  # repository, but a private repository that was created manually.
  contents: read

  # Grant read permissions to private container images.
  packages: read

on:
  push:
    paths:
      - '.github/workflows/clang-format.yml'
      - 'scripts/clang-format.sh'
      - '**.c'
      - '**.cpp'
      - '**.h'

  pull_request:
    paths:
      - '.github/workflows/clang-format.yml'
      - 'scripts/clang-format.sh'
      - '**.c'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/intel/fpga-runtime-for-opencl/ubuntu-20.04-clang:main

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run clang-format on source files
        run: ./scripts/clang-format.sh --verbose

      - name: ensure source files are unchanged
        run: git diff --exit-code
