# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# This workflow combines a pull-request flow that only builds the container,
# and a push flow that builds and pushes the container to the package registry.
#
# The push flow is triggered when the user pushes a commit to their personal,
# forked repository; in this case the container image is uploaded to their
# personal registry. The push flow is also triggered when a pull-request is
# merged into the main branch; in this case the container image is uploaded
# to the registry belonging to the runtime repository.
#
# This workflow design allows users to iterate and test container
# changes in their forked repository, while ensuring that only merged
# pull requests overwrite production images used by build workflows.

name: build container images

# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  # Grant read permissions to repository in case it is not a forked public
  # repository, but a private repository that was created manually.
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/container.yml'
      - 'container/rockylinux-8-dev/**'
      - 'container/rockylinux-9-dev/**'
      - 'container/debian-11-arm-dev/**'
      - 'container/opensuse-leap-15-dev/**'
      - 'container/ubuntu-18.04-dev/**'
      - 'container/ubuntu-20.04-dev/**'
      - 'container/ubuntu-22.04-dev/**'
      - 'scripts/install_aocl.sh'

  pull_request:
    paths:
      - '.github/workflows/container.yml'
      - 'container/rockylinux-8-dev/**'
      - 'container/rockylinux-9-dev/**'
      - 'container/debian-11-arm-dev/**'
      - 'container/opensuse-leap-15-dev/**'
      - 'container/ubuntu-18.04-dev/**'
      - 'container/ubuntu-20.04-dev/**'
      - 'container/ubuntu-22.04-dev/**'
      - 'scripts/install_aocl.sh'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      # If trigger-specific permissions were supported, write permissions to the
      # container registry would only be needed for push events.
      packages: write

    # This rebuilds all container images whenever any single Dockerfile is
    # changed. Therefore, when iterating on a container change, consider
    # temporarily commenting all but the container of interest below.
    strategy:
      matrix:
        container:
          - rockylinux-8-dev
          - rockylinux-9-dev
          - debian-11-arm-dev
          - opensuse-leap-15-dev
          - ubuntu-18.04-dev
          - ubuntu-20.04-dev
          - ubuntu-22.04-dev

    env:
      image: ghcr.io/${{ github.repository }}/${{ matrix.container }}

    continue-on-error: true

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # https://docs.docker.com/engine/reference/commandline/tag/#extended-description
      # > A tag name must be valid ASCII and may contain lowercase and
      # > uppercase letters, digits, underscores, periods and dashes.
      # > A tag name may not start with a period or a dash and may
      # > contain a maximum of 128 characters.
      - name: set container tag from git reference
        id: tag
        run: |
          ref=$(echo "$ref" | sed 's#^refs/\(\|heads/\|tags/\)##')
          echo "tag=${ref//[^a-zA-Z0-9_.]/-}" >> "$GITHUB_OUTPUT"
        env:
          ref: ${{ github.ref }}

      # Override uid of default user in container to align with GitHub-hosted runners
      # https://github.com/actions/checkout/issues/47
      - name: build image
        run: docker build --build-arg uid=1001 -t "$image:$tag" -f container/${{ matrix.container }}/Dockerfile .
        env:
          tag: ${{ steps.tag.outputs.tag }}

      - name: login to registry
        if: github.event_name == 'push'
        run: echo "$token" | docker login ghcr.io -u "$user" --password-stdin
        env:
          user: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push image to registry
        if: github.event_name == 'push'
        run: docker image push "$image:$tag"
        env:
          tag: ${{ steps.tag.outputs.tag }}
