# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Klocwork

permissions:
  # Grant read permissions to private container images.
  packages: read

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!**/.clang-format'
      - '!**/COPYING'
      - '!**/LICENSE'
      - '!.github/**'
      - '.github/workflows/klocwork.yml'
      - '!.gitignore'
      - '!cmake/manifests/**'
      - '!container/**'
      - '!docs/**'
      - '!scripts/**'

jobs:
  build:
    runs-on:
      - self-hosted
      - linux
      - x64
      - container

    container:
      image: ghcr.io/intel/fpga-runtime-for-opencl/ubuntu-22.04-dev:main
      volumes:
        - /opt/klocwork:/opt/klocwork

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release
      - run: echo /opt/klocwork/latest/bin >> "$GITHUB_PATH"
      - run: kwinject --output kwinject.out ninja -C build -v -k0
      - run: kwcheck create
      - run: kwcheck run --build-spec kwinject.out -F detailed --report kw-errors.txt
      - run: cat kw-errors.txt
      - uses: actions/upload-artifact@v3
        with:
          name: fpga-runtime-for-opencl-${{ github.sha }}-klocwork-${{ github.run_id }}
          path: kw-errors.txt
          if-no-files-found: error
